import type { Page } from '@playwright/test'
import { test, expect, dispatchWorkflowEvent, fetchWorkflowSnapshot } from '../fixtures/auth'
import { FIXTURE_IDS } from '../fixtures/ids'

/**
 * Spec 4 — admin-time-review → labor-payroll.
 *
 * Multi-workflow chain. The seed pre-creates:
 *   - one time_review_run row in `pending` (locks two labor_entries on APPROVE,
 *     period 2026-01-15)
 *   - a SIBLING labor_payroll_run in `generated` for a DIFFERENT period
 *     (2026-01-01 → 2026-01-14) — present only to honor the
 *     (company, period) UNIQUE constraint; this spec deliberately does NOT use
 *     it.
 *
 * Steps the admin walks through:
 *   1. APPROVE the time-review run (`pending → approved`). This enqueues
 *      `lock_labor_entries`; the worker locks the covered entries and the
 *      `generate_labor_payroll_run` drain then MATERIALISES a brand-new
 *      labor_payroll_run for the time-review's period.
 *   2. AUTO-GENERATION (WF-3). Assert that auto-generated run exists — poll
 *      `GET /api/labor-payroll-runs` for the run whose `time_review_run_id`
 *      matches THIS time-review run (NOT the pre-seeded sibling, whose
 *      `time_review_run_id` is null). This proves the time_review → payroll
 *      chain fires end-to-end, instead of leaning on a hand-seeded row.
 *   3. Drive the auto-generated run through the human handoff
 *      (`generated → approved → posting`), then assert the WORKER-DRIVEN
 *      terminal: poll until `state === 'posted'` with the QBO TimeActivity ids
 *      populated (the e2e worker drains the stubbed push in-window).
 */

type TimeReviewSnapshot = {
  state: 'pending' | 'approved' | 'rejected'
  state_version: number
}

type LaborPayrollSnapshot = {
  state: 'generated' | 'approved' | 'posting' | 'posted' | 'failed' | 'voided'
  state_version: number
  context: { qbo_payroll_batch_ref: string[] | null; time_review_run_id: string | null }
}

type LaborPayrollRunListRow = {
  id: string
  state: string
  time_review_run_id: string | null
}

const runSpec = process.env.E2E_RUN === '1' ? test : test.skip

/**
 * Poll the company-scoped labor-payroll-runs list until the worker's
 * `generate_labor_payroll_run` drain materialises a run for THIS time-review
 * run, then return its id. Fails the test if no auto-generated run appears
 * in-window.
 */
async function pollForAutoGeneratedRun(page: Page, timeReviewId: string): Promise<string> {
  let runId: string | null = null
  await expect
    .poll(
      async () => {
        const body = await fetchWorkflowSnapshot<{ laborPayrollRuns: LaborPayrollRunListRow[] }>(
          page,
          '/api/labor-payroll-runs',
        )
        const match = body.laborPayrollRuns.find((r) => r.time_review_run_id === timeReviewId)
        runId = match?.id ?? null
        return runId
      },
      {
        message: 'worker should auto-generate a labor_payroll_run for the approved time-review run',
        timeout: 30_000,
        intervals: [500, 1_000, 2_000],
      },
    )
    .not.toBeNull()
  return runId!
}

/**
 * Poll a labor-payroll snapshot until the e2e worker drives it to the `posted`
 * terminal with populated QBO TimeActivity ids, then return that snapshot.
 */
async function pollForPosted(page: Page, snapshotPath: string): Promise<LaborPayrollSnapshot> {
  let last: LaborPayrollSnapshot | null = null
  await expect
    .poll(
      async () => {
        last = await fetchWorkflowSnapshot<LaborPayrollSnapshot>(page, snapshotPath)
        const refs = last.context.qbo_payroll_batch_ref ?? []
        return last.state === 'posted' && refs.length > 0
      },
      {
        message: 'e2e worker should drive labor payroll posting → posted with QBO ids',
        timeout: 30_000,
        intervals: [500, 1_000, 2_000],
      },
    )
    .toBe(true)
  return last!
}

runSpec('admin approves time review then requests labor payroll post', { tag: '@payroll' }, async ({ adminPage }) => {
  const timeReviewId = FIXTURE_IDS.timeReviewRunId
  const timeReviewPath = `/api/time-review-runs/${timeReviewId}`
  const timeReviewEventsPath = `${timeReviewPath}/events`

  // 1. Time review: pending → approved (enqueues lock_labor_entries, which
  //    chains to generate_labor_payroll_run in the worker).
  const timeReviewBefore = await fetchWorkflowSnapshot<TimeReviewSnapshot>(adminPage, timeReviewPath)
  expect(timeReviewBefore.state).toBe('pending')

  const timeReviewAfter = await dispatchWorkflowEvent<TimeReviewSnapshot>(adminPage, timeReviewEventsPath, {
    event: 'APPROVE',
    state_version: timeReviewBefore.state_version,
  })
  expect(timeReviewAfter.state).toBe('approved')
  expect(timeReviewAfter.state_version).toBe(timeReviewBefore.state_version + 1)

  // 2. Assert the labor_payroll_run was AUTO-GENERATED off this time-review run
  //    (NOT the pre-seeded sibling). The auto-generated run is the only one
  //    carrying our time_review_run_id.
  const payrollId = await pollForAutoGeneratedRun(adminPage, timeReviewId)
  expect(payrollId).not.toBe(FIXTURE_IDS.laborPayrollRunId)

  const payrollPath = `/api/labor-payroll-runs/${payrollId}`
  const payrollEventsPath = `${payrollPath}/events`

  // The auto-generated run starts `generated` and links back to the time-review.
  const payrollBefore = await fetchWorkflowSnapshot<LaborPayrollSnapshot>(adminPage, payrollPath)
  expect(payrollBefore.state).toBe('generated')
  expect(payrollBefore.context.time_review_run_id).toBe(timeReviewId)

  // 3a. generated → approved.
  const payrollApproved = await dispatchWorkflowEvent<LaborPayrollSnapshot>(adminPage, payrollEventsPath, {
    event: 'APPROVE',
    state_version: payrollBefore.state_version,
  })
  expect(payrollApproved.state).toBe('approved')

  // 3b. POST_REQUESTED → posting. POST_SUCCEEDED is worker-only.
  const payrollPosting = await dispatchWorkflowEvent<LaborPayrollSnapshot>(adminPage, payrollEventsPath, {
    event: 'POST_REQUESTED',
    state_version: payrollApproved.state_version,
  })
  expect(payrollPosting.state).toBe('posting')

  // 3c. WORKER-DRIVEN TERMINAL: posting → posted (POST_SUCCEEDED) with QBO ids.
  const terminal = await pollForPosted(adminPage, payrollPath)
  expect(terminal.state).toBe('posted')
  expect(terminal.context.qbo_payroll_batch_ref?.length ?? 0).toBeGreaterThan(0)

  // UI cross-check: the detail screen reflects the worker-driven terminal.
  await adminPage.goto(`/financial/labor-payroll-runs/${payrollId}`)
  await expect(adminPage.getByText('posted', { exact: true })).toBeVisible({ timeout: 10_000 })
})
