// Public re-exports for the API layer.
//
// Screens import from '@/lib/api' rather than the per-resource modules so
// the directory layout can evolve without rippling through every caller.

export {
  apiDelete,
  apiGet,
  apiPatch,
  apiPost,
  ApiError,
  API_URL,
  NetworkError,
  getActiveCompanySlug,
  registerTokenProvider,
  request,
  setActiveCompanySlug,
  type RequestOptions,
  type TokenProvider,
} from './client'

export { queryKeys } from './keys'

export type {
  BootstrapResponse,
  BonusRuleRow,
  IntegrationMappingRow,
  LaborRow,
  MaterialBillRow,
  PricingProfileRow,
  ProjectAssignmentRow,
  ProjectRow,
  ProjectSummary,
  SessionResponse,
  WorkerRow,
} from './bootstrap'

export {
  dispatchProjectLifecycleEvent,
  fetchProjectLifecycle,
  type ProjectLifecycleHumanEvent,
  type ProjectLifecycleHumanEventEnvelope,
  type ProjectLifecycleSnapshot,
  type ProjectLifecycleState,
} from './project-lifecycle'

export {
  appendCaptureArtifacts,
  appendCaptureSessionEvents,
  createCaptureSession,
  discardCaptureSession,
  ensureCaptureSession,
  startCaptureSession,
  stopCaptureSession,
  type CaptureArtifactInput,
  type CaptureSessionEventInput,
  type CaptureSessionCreateInput,
  type CaptureSessionResponse,
} from './capture-sessions'

export {
  createSupportPacket,
  fetchSupportPacketAccessLog,
  fetchSupportPacket,
  type SupportPacketAccessLogEntry,
  type SupportPacketAccessLogResponse,
  type CreateSupportPacketInput,
  type CreateSupportPacketResponse,
  type SupportPacketDetail,
  type SupportPacketDetailResponse,
} from './support-packets'

export {
  appendWorkRequestEvent,
  createWorkRequest,
  dispatchWorkRequestToMesh,
  exportWorkRequestHandoffPacket,
  fetchWorkRequest,
  fetchWorkRequestBrief,
  fetchWorkRequestGithubExport,
  fetchWorkRequestHandoffPacket,
  fetchWorkRequestQueueHealth,
  fetchWorkRequests,
  retryWorkRequestMeshDispatch,
  reverseWorkRequest,
  useAppendWorkRequestEvent,
  useWorkRequests,
  type AppendWorkRequestEventInput,
  type AppendWorkRequestEventResponse,
  type ContextHandoffEvent,
  type ContextWorkItem,
  type CreateWorkRequestInput,
  type CreateWorkRequestResponse,
  type DispatchWorkRequestResponse,
  type ExportWorkRequestHandoffPacketInput,
  type ExportWorkRequestHandoffPacketResponse,
  type HandoffEventType,
  type ListWorkRequestsParams,
  type ListWorkRequestsResponse,
  type ReverseWorkRequestInput,
  type ReverseWorkRequestResponse,
  type WorkItemLane,
  type WorkItemSeverity,
  type WorkItemStatus,
  type WorkRequestBrief,
  type WorkRequestBriefResponse,
  type WorkRequestBriefTimelineEntry,
  type WorkRequestDetailResponse,
  type WorkRequestGithubExportResponse,
  type WorkRequestHandoffPacket,
  type WorkRequestHandoffPacketAudience,
  type WorkRequestHandoffPacketResponse,
  type WorkRequestQueueHealthResponse,
  type WorkRequestSupportPacketSummary,
} from './work-requests'

export {
  fetchIssueBoard,
  fetchIssueBoardItem,
  moveIssueBoardItem,
  normalizeIssueBoardFilters,
  useIssueBoard,
  useIssueBoardItem,
  useMoveIssueBoardItem,
  type IssueBoardColumn,
  type IssueBoardColumnId,
  type IssueBoardFilters,
  type IssueBoardGroupBy,
  type IssueBoardItem,
  type IssueBoardItemDetail,
  type IssueBoardLane,
  type IssueBoardResponse,
  type IssueBoardScope,
  type IssueBoardSeverity,
  type IssueBoardStatus,
  type IssueBoardTimelineEvent,
  type MoveIssueBoardItemInput,
} from './issue-board'

export {
  fetchAdminIssueBoard,
  normalizeAdminIssueBoardFilters,
  useAdminIssueBoard,
  type AdminIssueBoardColumn,
  type AdminIssueBoardFilters,
  type AdminIssueBoardItem,
  type AdminIssueBoardResponse,
} from './admin-issue-board'

export {
  clockIn,
  clockOut,
  fetchClockTimeline,
  useClockIn,
  useClockOut,
  useClockTimeline,
  useVoidClockEvent,
  voidClockEvent,
  type ClockEvent,
  type ClockEventSource,
  type ClockEventType,
  type ClockEventVoidRequest,
  type ClockEventVoidResponse,
  type ClockInRequest,
  type ClockInResponse,
  type ClockOutRequest,
  type ClockOutResponse,
  type ClockTimelineParams,
  type ClockTimelineResponse,
} from './clock'

export {
  createDailyLog,
  dailyLogPhotoUrl,
  deleteDailyLogPhoto,
  dispatchDailyLogEvent,
  fetchDailyLog,
  fetchDailyLogPhotos,
  fetchDailyLogs,
  fetchDailyLogSnapshot,
  patchDailyLog,
  submitDailyLog,
  uploadDailyLogPhoto,
  useCreateDailyLog,
  useDailyLog,
  useDailyLogPhotos,
  useDailyLogs,
  useDeleteDailyLogPhoto,
  usePatchDailyLog,
  useSubmitDailyLog,
  useUploadDailyLogPhoto,
  type DailyLog,
  type DailyLogCreateRequest,
  type DailyLogDetailResponse,
  type DailyLogHumanEvent,
  type DailyLogListParams,
  type DailyLogListResponse,
  type DailyLogPatchRequest,
  type DailyLogPhotoListResponse,
  type DailyLogPhotoMetadata,
  type DailyLogPhotoUploadOptions,
  type DailyLogPhotoUploadResponse,
  type DailyLogSnapshot,
  type DailyLogSnapshotContext,
  type DailyLogStatus,
  type DailyLogSubmitRequest,
  type UseUploadDailyLogPhotoInput,
} from './daily-logs'

export {
  createTimeReviewRun,
  dispatchTimeReviewEvent,
  fetchTimeReviewRun,
  fetchTimeReviewRuns,
  useCreateTimeReviewRun,
  useDispatchTimeReviewEvent,
  useTimeReviewRun,
  useTimeReviewRuns,
  type EntryAnomalies,
  type TimeAnomaly,
  type TimeAnomalyCode,
  type TimeReviewCreateRequest,
  type TimeReviewEventRequest,
  type TimeReviewHumanEvent,
  type TimeReviewListParams,
  type TimeReviewListResponse,
  type TimeReviewRunRow,
  type TimeReviewSnapshot,
  type TimeReviewState,
} from './time-review'

export {
  fetchVapidPublicKey,
  subscribePush,
  unsubscribePush,
  useSubscribePush,
  useUnsubscribePush,
  useVapidPublicKey,
  type PushSubscriptionRow,
  type SubscribeRequest,
  type SubscribeResponse,
  type VapidPublicKeyResponse,
} from './push'

export {
  fetchNotificationPreferences,
  updateNotificationPreferences,
  useNotificationPreferences,
  useUpdateNotificationPreferences,
  type NotificationChannel,
  type NotificationPreferences,
  type NotificationPreferencesResponse,
  type UpdateNotificationPreferencesRequest,
} from './prefs'

export {
  fetchNotifications,
  markNotificationRead,
  notificationQueryKeys,
  useMarkNotificationRead,
  useUnreadNotifications,
  type NotificationListParams,
  type NotificationListResponse,
  type NotificationReadResponse,
  type NotificationRow,
} from './notifications'

export {
  createWorker,
  fetchWorkers,
  useCreateWorker,
  useDeleteWorker,
  usePatchWorker,
  useWorkers,
  workerQueryKeys,
  type Worker,
  type WorkerCreateRequest,
  type WorkerListResponse,
  type WorkerPatchRequest,
} from './workers'

export {
  customerQueryKeys,
  fetchCustomers,
  useCreateCustomer,
  useCustomers,
  useDeleteCustomer,
  usePatchCustomer,
  type Customer,
  type CustomerCreateRequest,
  type CustomerListResponse,
  type CustomerPatchRequest,
} from './customers'

export { divisionQueryKeys, fetchDivisions, useDivisions, type Division, type DivisionListResponse } from './divisions'

export {
  createLaborEntry,
  laborEntryQueryKeys,
  patchLaborEntry,
  useCreateLaborEntry,
  usePatchLaborEntry,
  type LaborEntry,
  type LaborEntryCreateRequest,
  type LaborEntryPatchRequest,
} from './labor-entries'

export {
  fetchServiceItems,
  serviceItemQueryKeys,
  useCreateServiceItem,
  useDeleteServiceItem,
  usePatchServiceItem,
  useServiceItems,
  type ServiceItem,
  type ServiceItemCreateRequest,
  type ServiceItemListResponse,
  type ServiceItemPatchRequest,
} from './service-items'

export {
  fetchPricingProfiles,
  pricingProfileQueryKeys,
  useCreatePricingProfile,
  useDeletePricingProfile,
  usePatchPricingProfile,
  usePricingProfiles,
  type PricingProfile,
  type PricingProfileCreateRequest,
  type PricingProfileListResponse,
  type PricingProfilePatchRequest,
} from './pricing-profiles'

export {
  bonusRuleQueryKeys,
  fetchBonusRules,
  useBonusRules,
  useCreateBonusRule,
  useDeleteBonusRule,
  usePatchBonusRule,
  type BonusRule,
  type BonusRuleCreateRequest,
  type BonusRuleListResponse,
  type BonusRulePatchRequest,
} from './bonus-rules'

export {
  createEstimatePush,
  dispatchEstimatePushEvent,
  estimatePushLineRate,
  estimatePushLineUnit,
  estimatePushQueryKeys,
  fetchEstimatePush,
  fetchEstimatePushes,
  useCreateEstimatePush,
  useDispatchEstimatePushEvent,
  useEstimatePush,
  useEstimatePushes,
  type CreateEstimatePushResult,
  type EstimatePushHumanEvent,
  type EstimatePushLine,
  type EstimatePushListParams,
  type EstimatePushListResponse,
  type EstimatePushRow,
  type EstimatePushSnapshot,
  type EstimatePushState,
} from './estimate-pushes'

export {
  billingRunQueryKeys,
  dispatchBillingRunEvent,
  fetchBillingRun,
  fetchBillingRuns,
  useBillingRun,
  useBillingRuns,
  useDispatchBillingRunEvent,
  type BillingRunListParams,
  type BillingRunListResponse,
  type RentalBillingHumanEvent,
  type RentalBillingRunLine,
  type RentalBillingRunRow,
  type RentalBillingSnapshot,
  type RentalBillingState,
} from './billing-runs'

export {
  createLaborPayrollRun,
  fetchLaborPayrollRun,
  fetchLaborPayrollRuns,
  laborPayrollRunQueryKeys,
  previewLaborPayrollCoverage,
  useLaborPayrollRun,
  useLaborPayrollRuns,
  type LaborPayrollHumanEvent,
  type LaborPayrollPreviewResponse,
  type LaborPayrollRunListParams,
  type LaborPayrollRunListResponse,
  type LaborPayrollRunRow,
  type LaborPayrollSnapshot,
  type LaborPayrollState,
} from './labor-payroll-runs'

export {
  downloadPayrollExport,
  fetchPayrollExports,
  payrollExportDownloadPath,
  payrollExportQueryKeys,
  usePayrollExports,
  useRequestPayrollExport,
  PAYROLL_EXPORT_FORMATS,
  type PayrollExportFormat,
  type PayrollExportListResponse,
  type PayrollExportRow,
  type PayrollExportStatus,
} from './payroll-exports'

export {
  fetchQboAuthUrl,
  fetchQboConnection,
  fetchQboMappings,
  qboQueryKeys,
  useDeleteQboMapping,
  usePatchQboMapping,
  useQboConnection,
  useQboMappings,
  useTriggerQboSync,
  useUpsertQboMapping,
  type QboAuthUrlResponse,
  type QboConnection,
  type QboConnectionResponse,
  type QboEntityType,
  type QboMapping,
  type QboMappingListParams,
  type QboMappingListResponse,
  type QboMappingPatchRequest,
  type QboMappingUpsertRequest,
  type QboSyncStatus,
  type QboSyncTriggerResponse,
} from './qbo'

export {
  countFailedOutbox,
  dispatchQboSyncRunEvent,
  fetchQboSyncOutbox,
  fetchQboSyncRun,
  fetchQboSyncRuns,
  fetchQboSyncStatus,
  isQboSyncRunInFlight,
  qboSyncQueryKeys,
  qboSyncRunQueryKeys,
  useDispatchQboSyncRunEvent,
  useQboSyncOutbox,
  useQboSyncRun,
  useQboSyncRuns,
  useQboSyncStatus,
  type QboLatestSyncEvent,
  type QboSyncOutboxResponse,
  type QboSyncOutboxRow,
  type QboSyncRowStatus,
  type QboSyncRunContext,
  type QboSyncRunHumanEvent,
  type QboSyncRunListResponse,
  type QboSyncRunSnapshot,
  type QboSyncRunState,
  type QboSyncStatusConnection,
  type QboSyncStatusResponse,
} from './qbo-sync'

export {
  auditEventQueryKeys,
  fetchAuditEvents,
  useAuditEvents,
  type AuditEvent,
  type AuditEventListParams,
  type AuditEventListResponse,
} from './audit'

export {
  adminJobsQueryKeys,
  fetchAdminJobs,
  useAdminJobs,
  type AdminJobRun,
  type AdminJobStatus,
  type AdminJobsQueues,
  type AdminJobsResponse,
  type AdminQueueHealth,
} from './admin-jobs'

export {
  dispatchLaneQueryKeys,
  fetchDispatchLanes,
  pauseDispatchLane,
  resumeDispatchLane,
  useDispatchLanes,
  usePauseDispatchLane,
  useResumeDispatchLane,
  type DispatchLane,
  type DispatchLaneListResponse,
  type DispatchLaneState,
  type PauseLaneRequest,
  type ResumeLaneRequest,
} from './dispatch-lanes'

export {
  createWorkerIssue,
  useCreateWorkerIssue,
  type CreateWorkerIssueRequest,
  type CreateWorkerIssueResponse,
  type WorkerIssue,
  type WorkerIssueKind,
} from './issues'

export {
  suggestedSlugFromError,
  useCompanyModules,
  useCompanyProfile,
  useCompanySettings,
  useCreateCompany,
  useInviteMember,
  usePatchCompanyModules,
  usePatchCompanySettings,
  useUpdateCompanyProfile,
  useUpdateWorkingHours,
  useWorkingHours,
  type Company,
  type CompanyModules,
  type CompanyModulesResponse,
  type CompanyPortalSettings,
  type CompanyProfile,
  type CompanySettings,
  type CreateCompanyRequest,
  type CreateCompanyResponse,
  type CreateMembershipRequest,
  type WorkingHours,
  type WorkingHoursHoliday,
  type WorkingHoursOtRule,
  type WorkingHoursResponse,
  type WorkingHoursWeekday,
} from './companies'

export {
  useAcceptInvite,
  useCompanyInvites,
  useCompleteFirstRun,
  useCreateInvite,
  useInviteView,
  useRevokeInvite,
  type AcceptInviteResponse,
  type CompanyInvite,
  type CompleteFirstRunResponse,
  type CreateInviteRequest,
  type CreateInviteResponse,
  type InviteStatus,
  type InviteViewResponse,
  type ListInvitesResponse,
  type MembershipFirstRun,
  type PublicInviteView,
} from './invites'

export {
  useAssignMembershipRole,
  useCompanyRoles,
  useCreateCustomRole,
  useDeleteCustomRole,
  usePatchCustomRole,
  type AssignMembershipRoleRequest,
  type AssignMembershipRoleResponse,
  type BuiltinRoleView,
  type CompanyRolesResponse,
  type CreateCustomRoleRequest,
  type CustomRole,
  type CustomRoleGrant,
  type PatchCustomRoleRequest,
} from './company-roles'

export { useActiveCompanyId, useActiveCompanyModules } from './active-company'

export {
  copyScheduleWeek,
  fetchSchedules,
  scheduleQueryKeys,
  useCopyScheduleWeek,
  useSchedules,
  type CopyScheduleWeekRequest,
  type CopyScheduleWeekResponse,
  type CrewScheduleRow,
  type ScheduleListParams,
  type ScheduleListResponse,
} from './schedules'

export {
  crewScheduleQueryKeys,
  dispatchCrewScheduleEvent,
  fetchCrewScheduleSnapshot,
  patchCrewSchedule,
  useCrewScheduleSnapshot,
  useDispatchCrewScheduleEvent,
  type CrewScheduleEventRequest,
  type CrewScheduleHumanEvent,
  type CrewSchedulePatchRequest,
  type CrewScheduleSnapshot,
  type CrewScheduleState,
} from './crew-schedules'

export {
  fetchLaborBurdenToday,
  laborBurdenQueryKeys,
  useLaborBurdenToday,
  type LaborBurdenParams,
  type LaborBurdenSummaryResponse,
  type LaborBurdenWorkerResult,
} from './labor-burden'

export {
  fetchProjectLaborVariance,
  laborVarianceQueryKeys,
  useProjectLaborVariance,
  type LaborVarianceResponse,
  type LaborVarianceRow,
} from './labor-variance'

export {
  fetchProject,
  fetchProjects,
  projectQueryKeys,
  useProject,
  useProjectBriefs,
  useProjects,
  useProjectSummary,
  useProjectTimeline,
  type ProjectBrief,
  type ProjectBriefListResponse,
  type ProjectDetail,
  type ProjectDetailResponse,
  type ProjectListParams,
  type ProjectListResponse,
  type ProjectListRow,
  type ProjectStatus,
  type ProjectSummaryResponse,
  type ProjectSummaryEstimateLine,
  type ProjectSummaryLaborEntry,
  type ProjectTimelineEvent,
  type ProjectTimelineResponse,
} from './projects'

export {
  estimatePdfUrl,
  estimateQueryKeys,
  fetchScopeVsBid,
  isEstimateStale,
  recomputeEstimate,
  useScopeVsBid,
  type BidVsScopeStatus,
  type EstimateLine,
  type ScopeVsBidResponse,
} from './estimate'

export {
  useAddAssemblyComponent,
  useAddTakeoffTag,
  useAssemblies,
  useAssembly,
  useBlueprintDiffs,
  useBlueprintPages,
  useCalibratePage,
  useCreateAssembly,
  useCreateMeasurement,
  useDeleteMeasurement,
  usePatchMeasurement,
  useImportTakeoff,
  uploadBlueprint,
  useProjectBlueprints,
  useProjectMeasurements,
  useQboCustomFields,
  useRemoveTakeoffTag,
  useTakeoffTags,
  useUpdateTakeoffTag,
  useUploadBlueprint,
  useUpsertQboCustomField,
  useVerifyPage,
  type Assembly,
  type AssemblyComponent,
  type BlueprintDiffsResponse,
  type BlueprintDocument,
  type BlueprintPage,
  type BlueprintPageDiff,
  type CreateMeasurementInput,
  type ImportRow,
  type MeasurementGeometry,
  type QboCustomFieldMapping,
  type TakeoffMeasurement,
  type TakeoffTag,
  type UpdateTakeoffTagInput,
  type UploadBlueprintOptions,
  type UseUploadBlueprintInput,
} from './takeoff'

export {
  useConditions,
  useCreateCondition,
  useUpdateCondition,
  useDeleteCondition,
  type ConditionMeasurementKind,
  type CreateConditionInput,
  type TakeoffCondition,
  type UpdateConditionInput,
} from './conditions'

export {
  fileToBase64,
  useCostLibrary,
  useCreateCostLibraryItem,
  useImportCostLibrary,
  type CostLibraryItem,
  type CostLibraryListParams,
  type CostLibraryListResponse,
  type CreateCostLibraryItemInput,
  type ImportCostLibraryInput,
  type ImportCostLibraryResponse,
} from './cost-library'

export {
  captureBlueprintVisionLive,
  fetchBlueprintFile,
  useBlueprintVisionLiveAvailable,
  useCaptureBlueprintVisionLive,
  useCaptureTakeoffDraft,
  useCreateTakeoffDraft,
  useDeleteTakeoffDraft,
  useDuplicateTakeoffDraft,
  usePromoteCapturedQuantities,
  useTakeoffDrafts,
  useTakeoffDraftResult,
  useUpdateTakeoffDraft,
  type CaptureLiveInput,
  type CapturedGeometry,
  type CapturedGeometryObject,
  type CapturedGeometryRoom,
  type CapturedGeometrySurface,
  type CapturedQuantity,
  type CapturedTakeoffResult,
  type CaptureKind,
  type CaptureRequestBody,
  type CaptureResponse,
  type CaptureResultSummary,
  type DraftResultResponse,
  type PromoteRequestBody,
  type PromoteResponse,
  type TakeoffDraft,
} from './takeoff-drafts'

export {
  useAiInsights,
  useApplyInsight,
  useBidAccuracy,
  useDismissInsight,
  useTriggerBidFollowUp,
  useTriggerTakeoffToBid,
  useTriggerVoiceToLog,
  type AccuracyConfidence,
  type AiInsight,
  type BidAccuracyProject,
  type BidAccuracySummary,
  type BidFollowUpDraft,
  type InsightListParams,
  type TakeoffToBidPayload,
  type TakeoffToBidProposal,
  type VoiceToLogProposal,
} from './ai'

export {
  fetchInventoryUtilizationSummary,
  listInventoryItems,
  listInventoryLocations,
  useCreateContractLine,
  useCreateInventoryItem,
  useCreateInventoryLocation,
  useCreateRentalContract,
  useDeleteContractLine,
  useDeleteInventoryItem,
  useDeleteInventoryLocation,
  useDispatchMovement,
  useGenerateBillingRun,
  useInventoryForecast,
  useInventoryItems,
  useInventoryLocations,
  useInventoryMovements,
  useInventoryUtilization,
  usePatchContractLine,
  usePatchInventoryItem,
  usePatchInventoryLocation,
  usePatchRentalContract,
  usePreviewBillingRun,
  useProjectRentalContracts,
  useCreateRentalRateTier,
  useDeleteRentalRateTier,
  useRentalContractLines,
  useRentalRateTiers,
  useRentalReturn,
  useRentalTransfer,
  type BillingRunPreview,
  type ContractCreateRequest,
  type ContractLineCreateRequest,
  type ContractLineListResponse,
  type ContractLinePatchRequest,
  type ContractListResponse,
  type ContractPatchRequest,
  type ForecastResponse,
  type ForecastWeek,
  type InventoryItem,
  type InventoryItemCreateRequest,
  type InventoryItemPatchRequest,
  type InventoryLocation,
  type InventoryLocationCreateRequest,
  type InventoryLocationPatchRequest,
  type InventoryMovement,
  type InventoryUtilizationSummary,
  type InventoryUtilizationTopItem,
  type JobRentalContract,
  type MovementListParams,
  type RentalContractLine,
  type RentalRateTier,
  type RentalRateTierCreateRequest,
  type RentalRateTierListResponse,
  type RentalRateUnit,
  type RentalReturnRequest,
  type RentalRow,
  type RentalTransferRequest,
  type RentalTransferResponse,
  type ScanDispatchInput,
  type UtilizationRow,
  type UtilizationTopItem,
  type UtilizationTotals,
} from './rentals'

export {
  useApproveRentalRequest,
  useDeclineRentalRequest,
  useRentalRequests,
  useRentalRequestSnapshot,
  useDispatchRentalRequestEvent,
  fetchRentalRequestSnapshot,
  dispatchRentalRequestEvent,
  type ApproveRentalRequestInput,
  type ApproveRentalRequestResponse,
  type DeclineRentalRequestInput,
  type DeclineRentalRequestResponse,
  type RentalRequest,
  type RentalRequestItem,
  type RentalRequestListResponse,
  type RentalRequestStatus,
  type RentalRequestSnapshot,
  type RentalRequestApprovalState,
  type RentalRequestApprovalEvent,
} from './rental-requests'

// Phase 3.1 — admin notification queue (isolated block; see notifications-queue.ts)
export {
  fetchNotificationQueue,
  notificationQueueKeys,
  useDispatchNotificationEvent,
  useNotificationQueue,
  type NotificationQueueListParams,
  type NotificationQueueListResponse,
  type NotificationQueueRow,
  type NotificationSnapshot,
} from './notifications-queue'
