import { useEffect, useRef } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { MBanner, MBody, MButton, MButtonStack, MTextarea, MTopBar } from '@/components/m'
import {
  usePortalEstimateSignature,
  type PortalEstimateSignatureHookResult,
} from '@/machines/portal-estimate-signature'
import { registerCaptureStateProvider } from '@/lib/capture-state-providers'
import { type PortalEstimateView } from './api'
import { IssueReporter } from './IssueReporter'
import { SignatureCapture } from './SignatureCapture'

/**
 * Public-facing estimate review screen for clients. Mounted at
 * `/portal/estimates/:shareToken` (no Clerk auth, no company picker).
 *
 * The page is a single-screen review of a frozen estimate snapshot
 * with two terminal CTAs (Accept + Decline). Mobile-first layout —
 * pure light theme so the customer never sees the operator's dark
 * mode chrome.
 *
 * State (load / accept / decline / submit error / signer fields) is
 * owned by the `portalEstimateSignature` XState machine. This
 * component is a thin renderer; the only side effect it owns is
 * react-router navigation (the machine signals
 * `shouldRedirectAccepted` and we call `navigate(...)` from a
 * `useEffect`).
 */
export function EstimateView() {
  const { shareToken } = useParams<{ shareToken: string }>()
  const token = shareToken ?? ''
  const navigate = useNavigate()
  const signature = usePortalEstimateSignature(token)
  useEstimatePortalCaptureStateProvider(token, signature)

  // The machine signals when it's time to navigate into the accepted
  // view. Doing the navigation here (instead of inside an XState
  // action) keeps the machine framework-free, matching the existing
  // `submit-form.ts` / `estimate-share.ts` convention.
  useEffect(() => {
    if (signature.shouldRedirectAccepted && shareToken) {
      navigate(`/portal/estimates/${shareToken}/accepted`, { replace: true })
    }
  }, [signature.shouldRedirectAccepted, shareToken, navigate])

  if (signature.loadError) {
    return (
      <Shell title="Estimate" shareToken={token}>
        <MBanner tone="error" title={signature.loadError.message} />
      </Shell>
    )
  }

  const view = signature.view
  if (!view) {
    return (
      <Shell title="Estimate" shareToken={token}>
        <div style={{ padding: 24, textAlign: 'center', color: 'var(--m-ink-3, var(--p-slate-ink-3))', fontSize: 14 }}>
          Loading…
        </div>
      </Shell>
    )
  }

  if (view.status === 'declined') {
    return (
      <Shell title={view.project_name} sub={`From ${view.company_name}`} shareToken={token}>
        <MBanner
          tone="warn"
          title="You declined this estimate."
          body={view.decline_reason ? `Reason: ${view.decline_reason}` : undefined}
        />
        <ReadOnlySnapshot view={view} />
      </Shell>
    )
  }

  if (view.status === 'expired') {
    return (
      <Shell title={view.project_name} sub={`From ${view.company_name}`} shareToken={token}>
        <MBanner tone="warn" title="This link has expired." body="Contact the sender for a fresh link." />
      </Shell>
    )
  }

  // The user-facing submit-time error is either the machine's
  // `submitError` (from a failed network call) or the inline
  // validation hint generated by the machine when the form is
  // incomplete.
  const inlineError =
    signature.submitError ??
    (signature.mode === 'accepting'
      ? signature.acceptValidationMessage
      : signature.mode === 'declining'
        ? signature.declineValidationMessage
        : null)

  return (
    <Shell title={view.project_name} sub={`From ${view.company_name}`} shareToken={token}>
      <ReadOnlySnapshot view={view} />

      {signature.mode === 'idle' ? (
        <>
          {signature.submitError ? <MBanner tone="error" title={signature.submitError} /> : null}
          <MButtonStack>
            <MButton variant="primary" onClick={signature.startAccept}>
              Accept estimate
            </MButton>
            <MButton variant="quiet" onClick={signature.startDecline}>
              Decline
            </MButton>
          </MButtonStack>
        </>
      ) : null}

      {signature.mode === 'accepting' ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          <h3 style={{ margin: 0, fontSize: 15, fontWeight: 600 }}>Sign to accept</h3>
          <p style={{ margin: 0, fontSize: 13, color: 'var(--m-ink-3, var(--p-slate-ink-3))' }}>
            Type your full name and sign below. By accepting you agree to the line items and totals shown above.
          </p>

          <label style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
            <span style={{ fontSize: 12, color: 'var(--m-ink-3, var(--p-slate-ink-3))' }}>Your full name</span>
            <input
              className="m-input"
              value={signature.signerName}
              onChange={(e) => signature.setSignerName(e.target.value)}
              autoComplete="name"
              placeholder="Jane Doe"
            />
          </label>

          <SignatureCapture onChange={signature.setSignature} />

          {inlineError ? <MBanner tone="error" title={inlineError} /> : null}

          <MButtonStack>
            <MButton variant="primary" onClick={signature.submitAccept} disabled={signature.isSubmitting}>
              {signature.isSubmittingAccept ? 'Submitting…' : 'Submit acceptance'}
            </MButton>
            <MButton variant="quiet" onClick={signature.cancel} disabled={signature.isSubmitting}>
              Cancel
            </MButton>
          </MButtonStack>
        </div>
      ) : null}

      {signature.mode === 'declining' ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          <h3 style={{ margin: 0, fontSize: 15, fontWeight: 600 }}>Decline this estimate</h3>
          <p style={{ margin: 0, fontSize: 13, color: 'var(--m-ink-3, var(--p-slate-ink-3))' }}>
            Optionally tell us why so we can follow up with adjustments.
          </p>
          <MTextarea
            value={signature.declineReason}
            onChange={(e) => signature.setDeclineReason(e.target.value)}
            rows={4}
            placeholder="Reason"
            maxLength={2000}
          />

          {inlineError ? <MBanner tone="error" title={inlineError} /> : null}

          <MButtonStack>
            <MButton variant="primary" onClick={signature.submitDecline} disabled={signature.isSubmitting}>
              {signature.isSubmittingDecline ? 'Submitting…' : 'Submit decline'}
            </MButton>
            <MButton variant="quiet" onClick={signature.cancel} disabled={signature.isSubmitting}>
              Cancel
            </MButton>
          </MButtonStack>
        </div>
      ) : null}
    </Shell>
  )
}

function ReadOnlySnapshot({ view }: { view: PortalEstimateView }) {
  const lines = view.estimate.lines
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      <header
        style={{
          display: 'flex',
          flexDirection: 'column',
          gap: 4,
          padding: '12px 16px',
          background: 'var(--p-slate-soft)',
          border: '1px solid var(--m-line, var(--p-slate-line))',
          borderRadius: 12,
        }}
      >
        <span style={{ fontSize: 12, color: 'var(--m-ink-3, var(--p-slate-ink-3))' }}>
          Sent {formatDate(view.sent_at)} · expires {formatDate(view.expires_at)}
        </span>
        {view.recipient_name || view.recipient_email ? (
          <span style={{ fontSize: 13 }}>
            For: {view.recipient_name ? `${view.recipient_name} · ` : ''}
            <span style={{ color: 'var(--m-ink-3, var(--p-slate-ink-3))' }}>{view.recipient_email}</span>
          </span>
        ) : null}
      </header>

      <section
        style={{
          background: 'var(--p-paper)',
          border: '1px solid var(--m-line, var(--p-slate-line))',
          borderRadius: 12,
          overflow: 'hidden',
        }}
      >
        <div
          style={{
            padding: '12px 16px',
            borderBottom: '1px solid var(--m-line, var(--p-slate-line))',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
          }}
        >
          <span style={{ fontSize: 13, fontWeight: 600 }}>Line items</span>
          <span style={{ fontSize: 12, color: 'var(--m-ink-3, var(--p-slate-ink-3))' }}>{lines.length} items</span>
        </div>
        <ul style={{ listStyle: 'none', margin: 0, padding: 0 }}>
          {lines.map((line) => (
            <li
              key={`${line.service_item_code}-${line.quantity}-${line.rate}`}
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                gap: 12,
                padding: '12px 16px',
                borderBottom: '1px solid var(--m-line, var(--p-slate-line))',
              }}
            >
              <div style={{ minWidth: 0, flex: 1 }}>
                <div style={{ fontSize: 13, fontWeight: 500 }}>{line.service_item_code}</div>
                <div style={{ fontSize: 12, color: 'var(--m-ink-3, var(--p-slate-ink-3))' }}>
                  {line.quantity.toLocaleString()} {line.unit} × ${line.rate.toFixed(2)}
                </div>
              </div>
              <div style={{ fontSize: 13, fontWeight: 600, textAlign: 'right' }}>
                ${line.amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </div>
            </li>
          ))}
        </ul>
        <div
          style={{
            padding: '14px 16px',
            display: 'flex',
            justifyContent: 'space-between',
            background: 'var(--p-slate-soft)',
          }}
        >
          <span style={{ fontSize: 14, fontWeight: 600 }}>Total</span>
          <span style={{ fontSize: 18, fontWeight: 700 }}>
            $
            {view.estimate.bid_total.toLocaleString(undefined, {
              minimumFractionDigits: 2,
              maximumFractionDigits: 2,
            })}
          </span>
        </div>
      </section>
    </div>
  )
}

function Shell({
  title,
  sub,
  shareToken,
  children,
}: {
  title: string
  sub?: string
  shareToken: string
  children: React.ReactNode
}) {
  // Force the light theme regardless of OS preference; the operator's
  // mobile shell switches to dark on some screens, but customer-facing
  // surfaces stay strictly light per the spec.
  return (
    <div
      data-theme="light"
      style={{ minHeight: '100vh', background: 'var(--p-slate-bg)', color: 'var(--p-slate-ink)' }}
    >
      <MTopBar title={title} sub={sub} />
      <MBody pad>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 18, paddingTop: 12, paddingBottom: 32 }}>
          {children}
        </div>
      </MBody>
      {/* Invited-guest issue-report pill. Renders null unless an invite token
          is present so public share links stay inert by default. */}
      <IssueReporter surface="estimate_portal" shareToken={shareToken} />
    </div>
  )
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })
  } catch {
    return iso
  }
}

function useEstimatePortalCaptureStateProvider(
  shareToken: string,
  signature: PortalEstimateSignatureHookResult,
): void {
  const signatureRef = useRef(signature)
  signatureRef.current = signature

  useEffect(() => {
    if (!shareToken) return undefined
    return registerCaptureStateProvider('portal:estimate', ({ reason }) => {
      const state = signatureRef.current
      const view = state.view
      return {
        schema: 'sitelayer.portal.estimate-state.v1',
        payload: {
          surface: 'estimate_portal',
          route_template: '/portal/estimates/:shareToken',
          share_token_present: true,
          reason,
          is_loading: state.isLoading,
          mode: state.mode,
          submit_error_present: Boolean(state.submitError),
          accept_validation_present: Boolean(state.acceptValidationMessage),
          decline_validation_present: Boolean(state.declineValidationMessage),
          draft: {
            signer_name_length: state.signerName.trim().length,
            signature_present: Boolean(state.signature),
            decline_reason_length: state.declineReason.trim().length,
          },
          load_error: state.loadError
            ? {
                status: state.loadError.status,
                message: truncateForCapture(state.loadError.message),
              }
            : null,
          estimate: view
            ? {
                id: view.id,
                status: view.status,
                sent_at: view.sent_at,
                expires_at: view.expires_at,
                accepted: Boolean(view.accepted_at),
                declined: Boolean(view.declined_at),
                has_decline_reason: Boolean(view.decline_reason),
                has_recipient: Boolean(view.recipient_name || view.recipient_email),
                bid_total: view.estimate.bid_total,
                scope_total: view.estimate.scope_total,
                line_count: view.estimate.lines.length,
                captured_at: view.estimate.captured_at,
                truncated: view.estimate.lines.length > 20,
                lines: view.estimate.lines.slice(0, 20).map((line, index) => ({
                  index,
                  service_item_code: line.service_item_code,
                  quantity: line.quantity,
                  unit: line.unit,
                  division_code: line.division_code,
                  amount: line.amount,
                })),
              }
            : null,
        },
        piiLevel: 'internal' as const,
        metadata: {
          portal_surface: 'estimate_portal',
          route_template: '/portal/estimates/:shareToken',
        },
      }
    })
  }, [shareToken])
}

function truncateForCapture(value: string): string {
  return value.length > 500 ? value.slice(0, 500) : value
}
